### ISSUE TITLE
UI Export Big Data , UI Date picker 

### ISSUE THREAD

**Issue by basharsvu** [alanjuden/MvcReportViewer#18]
Dear,

I have two issues in the UI :

1- The Export functionally when the data are big more than 100000 records, it comes with exception.
2- Calendar Date picker not showing  when its used in the report.

Thanks

**Comment by alanjuden** [comment]
@basharsvu,

1. Could you give any more detail as to the error that's occurred with large amounts of data? Is it happening client side or server side?
2. I usually prefer to handle the date picker code through a simple javascript (mine is handled site wide by targeting the input type of "datetime"). Handling the date picker client side allows you to use a control of your choice rather than the browser built-in. However, you could modify the logic that adds that "type" on the date inputs to use "date" or "datetime-local" to get the built in browser date control. I tested out the "datetime-local" input type and chrome didn't behave until I had fully entered the date and time the parameter was passed as blank.

Alan

**Comment by basharsvu** [comment]
Thank you Dear, 
Regarding the error for big data , its happening in the server side , due to timeout error, and this is also same problem when you connect to any report at the first time ?! because second time it will be cashed so no time out errors.

So the thing is to figure out a way to optimize the first request to the server , and increase the time out for exporting the big data.

**Comment by alanjuden** [comment]
@basharsvu, check out the latest version that I pushed out there a couple days ago. It allows you to override the timeout value for your reports. You would setup the override on your custom report controller. 

**If you need an infinite amount of time you could use the following:**

protected override int? Timeout
		{
			get
			{
				return System.Threading.Timeout.Infinite;
			}
		}

**Or something more like 5 minutes using this:**

protected override int? Timeout
		{
			get
			{
				return 300;
			}
		}
