### ISSUE TITLE
SetParameters causing dictionary collision

### ISSUE THREAD

**Issue by mtinnes** [alanjuden/MvcReportViewer#20]
The SetParameters() function in ReportExportResult is using the report parameter label as a key, which is causing a collision with our dataset. The offending code is:

```
if (definedReportParameter.ValidValues != null)
{
  foreach (var validValue in definedReportParameter.ValidValues)
  {
    reportParameter.ValidValues.Add(validValue.Label, validValue.Value);
  }
}
```

check needed before inserting into ValidValues

**Comment by alanjuden** [comment]
@mtinnes: could you give me any more info about the setup of your report? The "validValue" object is coming from the SSRS api (from definedReportParameter.ValidValues). 

Could you maybe explain the parameters in use on your report as well as if you have any duplicated values that are valid values in the option list? If your issue is coming from the ValidValues.Add line then it indicates you have more than one value with the same name in your parameter's "Available Values" section of your report.

SSRS only provides two fields for me to use on the available values (Label, and Value). Just as defined in reports.

I've attached a picture of a sample report on where to be checking for duplicates.

![image](https://cloud.githubusercontent.com/assets/1704632/23928795/e77454e6-08ef-11e7-852a-f7430fd94b8a.png)

*notice you only have two fields (Label and Value).*

I'm totally willing to help here just looking for what's actually happening as I haven't run into this issue myself.

**Comment by mtinnes** [comment]
Thanks @alanjuden, you are right on, we have values which have identical labels. I don't see that the dictionary is being used and could possibly be changed to a simple list?
