### ISSUE TITLE
Server Error in '/' Application

### ISSUE THREAD

**Issue by deanilvincent** [alanjuden/MvcReportViewer#40]
I'm having an issue. I just freshly installed the package for my asp.net mvc 5 application but I'm having this error

![bug01](https://user-images.githubusercontent.com/10904957/31324608-f252ccee-ace6-11e7-9b01-1412ecefac21.PNG)

Thank you in advance

**Comment by alanjuden** [comment]
@deanilvincent, this is because you're using my master page template which has sections defined for AdditionalHeadContent (which could be set to not required on the master page file) and Content which is like your BodyContent. If you just edit your page to include those two sections, you should be working.

**Comment by AlwaysAbhl001** [comment]
@alanjuden  If I did so.. 

![report](https://user-images.githubusercontent.com/26591838/31600417-f8531e5e-b273-11e7-8945-84fcbf497bc4.JPG)

What would be the reason?
