### ISSUE TITLE
Time Out Problem

### ISSUE THREAD

**Issue by basharsvu** [alanjuden/MvcReportViewer#48]
Dear,

Am setting the Time out Parameter to the infinite but actually am still facing time out issue after 2 mints 
any idea please

**Comment by alanjuden** [comment]
@basharsvu, 

Here are things I would check:

1. Have you checked the timeout value that's specified in your report itself? 
2. Does the report work just fine when you're using the regular report server? 
3. Open Chrome Developer Tools and see if the website is timing out on the request rather than the SSRS api.

Hope this helps.

Alan

**Comment by basharsvu** [comment]
Yes Thank you.
