### ISSUE TITLE
Export and Paging Another hit on the Server

### ISSUE THREAD

**Issue by basharsvu** [alanjuden/MvcReportViewer#53]
Dear,

Acautly the Export and pagination took another hit on the report server, while in the report server it self when you view the report you can export it directly because the data already exist on the first round.

Could please explain this, and is there any why to make only one round trip to the report server.?

Thanks

**Comment by alanjuden** [comment]
Hey @basharsvu, yes - export and pagination do hit the server also. My code is requesting the reports 1 page at a time in html format. So if you wanted to export into Excel, it makes a request for ALL pages and it's also in Excel format rather than HTML format. 

However, on the model, you can disable paging by using the "EnablePaging" property set to false. Which will load ALL pages in one request but it's not very pretty. It also removes the paging control from the report viewer.

I hope this helps.

Alan
