### ISSUE TITLE
Trouble Rendering Report Parts

### ISSUE THREAD

**Issue by nbw71791** [alanjuden/MvcReportViewer#61]
I am having trouble rendering report parts in my .Net Core app using the MvcReportViewer.NetCore package.

Using the UseCustomReportImagePath, is there a specific way that I should format the ReportImagePath parameter to direct the renderer to my report parts?

Regardless of what I try (UseCustomReportImagePath = false, UseCustomReportImagePath = true, UseCustomReportImagePath & ReportImagePath = "PathToWhereMyReportPartsArePublished"), I keep getting the same error:

**Reporting Services Error**
The stream cannot be found. The stream identifier that is provided to an operation cannot be located in the report server database. (rsStreamNotFound)

Any help would be greatly appreciated!

**Comment by alanjuden** [comment]
Hey @nbw71791, I would think your report parts should be coming down as html code rather than as images but don't quote me on that :)

The purpose of the UseCustomReportImagePath = true and ReportImagePath set to something, are in case you need the server to reach inside your network for the images. It's kind of setting up a proxy to where someone navigating to your MVC site hits a link on your site, but your site then forwards the request to your internal SSRS server. The only reason you would need to modify the "ReportImagePath" would be if you named your ReportController anything other than "ReportController".

I hope this helps.

Alan

**Comment by nbw71791** [comment]
Hi Alan, thanks for the insight. It turned out to be a credential issue. A new AD account I had created for the app had permissions on the report server for the reports but not report parts.

My mistake.

Thank you!
