### ISSUE TITLE
Get report content in with Ajax, report is not public accessible

### ISSUE THREAD

**Issue by 82949712** [alanjuden/MvcReportViewer#68]
Hi, 

Looking at the sample code, it seems the report content is loaded using an Ajax, but if we only rely on windows authentication, and the SSRS address is not publicly accessible, how will the client be able to download the report in the browser?

Thanks

**Comment by alanjuden** [comment]
@82949712, I have a similar situation and it's working fine. My web server is on the same network as my SSRS server. Which is all you really need to be accessed from your website. The reason that it works is because it's an ajax call and the content is requested from your web server which is on the same network as SSRS and streamed back to and displayed in HTML format on the webserver. 

Hope this helps!

Alan

**Comment by 82949712** [comment]
@alanjuden  Thank you for your answer. Actually I didn't check it properly, the ajax is only to the ViewReportPage url not to the actual SSRS server, I thought the ajax was directly to the ssrs.

**Comment by mkumar9699** [comment]
Want to call report from javascript ajax on button click with parameters in asp.net core mvc
