### ISSUE TITLE
LocalReport Mode Support?

### ISSUE THREAD

**Issue by yarmenteros** [alanjuden/MvcReportViewer#7]
First at all, congratulation, you're doing a great job.

My question is simple, I need to know if can I use your library in an ASP.NET Core project for RDLC files stored in my local file system.

Thanks in advance.

**Comment by alanjuden** [comment]
Thanks for asking the question, at this moment, I don't have any intention to support LocalReport Mode due to the fact that all of my "logic" is using the Report Server to handle the report generation. That would involve making my own renderer for the reports which I don't believe I'm going to do. This was fairly straight forward for the Server Reports Mode due to the fact I'm just hooking into an existing SSRS api.
