### ISSUE TITLE
Don't attempt pre-load reports if not all required parameters are filled

### ISSUE THREAD

**Issue by adopilot** [alanjuden/MvcReportViewer#8]
First thanks a lot on effort making this.
I hope that this is going to be more and more robust.

There is AjaxLoadInitialReport 
But for me looks like that has inverse logic.
When AjaxLoadInitialReport is set to false . Reports load initially on lending on view.
It is just a whatnot but It took me for while.
I came to complain about missing feature and before Subnit Issue i Try to set it to false.
And it is woking as shoud

Thaks again
Please keep going

**Comment by alanjuden** [comment]
@adopilot, thanks for reaching out to me and thanks for checking out my code!

The AjaxLoadInitialReport is used to determine if the report should be generated when the page loads immediately (AjaxLoadInitialReport = false) or should the report be generated after the initial page load (AjaxLoadInitialReport = true).

I think what you're really getting at is that I'm trying to load the report before you've filled in any parameters, is that correct? In my instances of reports I usually fill defaults into the parameter fields so that the report can still load the first time. I suppose 

I should look at giving people the option to not have the report load until after you've filled out parameters.

Alan

**Comment by adopilot** [comment]
It is perfectly  fine to have control will report be rendered or not.
But I try only to point that this should   be default.
I was confused because it has to be  AjaxLoadInitialReport   = false to preform auto load.
For me more logic is to AjaxLoadInitialReport   = true preform initial load.
